### ISSUE TITLE
picture&components.js

### ISSUE THREAD

**Issue by grynov** [neliudochka/pixel-toons-polychchja#11]
when you have created the Picture class, you forgot to make "palette" an attribute, which leads to the problem on line 17 when you try to access it

https://github.com/neliudochka/pixel-toons-polychchja/blob/162089a79703afbb58a59b10977c3a28523c6e9a/public/scripts/picture%26components.js#L17

**Comment by neliudochka** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/pull/13
