### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by hoshion** [neliudochka/pixel-toons-polychchja#2]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/gameOfLife.js#L20

making state of game as a class

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/canvas.js#L42
magic value

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/canvas.js#L3
it will be better to add all functions below to this class

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/gameOfLife.js#L55
it will be better to change this line to 
`if (arrayOfCells[index].isAlive) {
  numAlive--;
}`

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/gameOfLife.js#L51
the logic in brackets should be a constant variable above

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/gameOfLife.js#L51
it will be better to change this line to
`if (arrayOfCells[name of constant].isAlive()) {
  numAlive++;
}`

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/picture%26components.js#L1
bad naming of file

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/picture%26components.js#L50
misunderstanding name of function. rather better makeOld or smth else

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/picture%26components.js#L67
wrap scope with braces for better reading

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/reflect.js#L1

decompose function. (better create class PictureReflector and create all methods inside it)

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/reflect.js#L20
bad naming of variable

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/index.js#L10
better create separate file for options

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/canvas.js#L10
this condition statement can be changed to:

`if (this.picture !== picture) { ...code from else... }`

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/canvas.js#L57
magic value

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/canvas.js#L59
double looping is a bad practice

**Comment by hoshion** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/blob/a5b34b3b0d265f15acf5ce672cce7c54f26665c9/public/scripts/gameOfLife.js#L20
decompose such a big function

**Comment by neliudochka** [comment]
https://github.com/neliudochka/pixel-toons-polychchja/pull/5
